global_args:
  trainer_backend: pl
  enable_deepspeed: false
  enable_ptv2: false
  enable_lora: false
  load_in_bit: 0
  config_merge: {}
  # 模型权重 ， 对应 config.constant_map.py
  model_name: mit-b0

  # one of auto 16 bf16 32
  precision: auto
  quantization_config:
    load_in_8bit: false
    load_in_4bit: false
    llm_int8_threshold: 6.0
    llm_int8_has_fp16_weight: false
    bnb_4bit_compute_dtype: float16  # one of float16  bfloat16 float32
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4





# https://huggingface.co/nvidia/segformer-b3-finetuned-ade-512-512
# https://huggingface.co/nvidia/segformer-b5-finetuned-cityscapes-1024-1024

# See all SegFormer models at https://huggingface.co/models?filter=segformer

global_models_mapper:
    mit-b0:
        model_type: segformer
        model_name_or_path: /data/nlp/pre_models/torch/segformer/mit-b0
        config_name: /data/nlp/pre_models/torch/segformer/mit-b0/config.json
        tokenizer_name: /data/nlp/pre_models/torch/segformer/mit-b0

    segformer-b0-finetuned-ade-512-512:
        model_type: segformer
        model_name_or_path: /data/nlp/pre_models/torch/segformer/segformer-b0-finetuned-ade-512-512
        config_name: /data/nlp/pre_models/torch/segformer/segformer-b0-finetuned-ade-512-512/config.json
        tokenizer_name: /data/nlp/pre_models/torch/segformer/segformer-b0-finetuned-ade-512-512


    segformer-b5-finetuned-cityscapes-1024-1024:
        model_type: segformer,
        model_name_or_path: /data/nlp/pre_models/torch/segformer/segformer-b5-finetuned-cityscapes-1024-1024
        config_name: /data/nlp/pre_models/torch/segformer/segformer-b5-finetuned-cityscapes-1024-1024/config.json
        tokenizer_name: /data/nlp/pre_models/torch/segformer/segformer-b5-finetuned-cityscapes-1024-1024
